---
install:
  - cpanm --notest App::mymeta_requires Module::Build
  - perl Build.PL
  - ./Build manifest
  - perl Build.PL
  - mymeta-requires --runtime --build --test --configure --develop --recommends --suggests | cpanm
language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
